# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master

trigger:
- master
- test

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:

  - stage: BuildAndPush
    displayName: Build image
    jobs: 
    - job: Build
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/test'))
      displayName: Build
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: Docker@2
          displayName: Build and Push
          inputs:
            containerRegistry: 'graziela|azure'
            repository: '1.0'
            command: buildAndPush
            Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
            tags: |
              $(Build.BuildId)
              latest


  - stage: Run
    displayName: Run image
    jobs:  
    - job: Run
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      displayName: Run
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: CmdLine@2
        displayName: Validate connection
        inputs:
          script: curl -v https://lottocap.com.br
      - task: Docker@2
        displayName: Login to ACR
        inputs:
          command: login
          containerRegistry: graziela|azure
      - task: CmdLine@2
        displayName: Pull image
        inputs:
          script: 'docker pull graziela.azurecr.io/1.0:latest' 
      - task: CmdLine@2
        displayName: Running tests
        inputs:
          script: 'docker run -e URI_HOMOLOG=https://api-qa2.lottocap.com.br/api  -e URIPROD="https://api.lottocap.com.br/api"  -e DATABASE_USERNAME="Lottocap"  -e DATABASE_PASSWORD="L0ttocap19!12@"  -e DATABASE_HOST="hmllottocap.database.windows.net"  -e DATABASE_PORT=1433  -e DATABASE_DATABASE="hmllottocaptests"  -e DATABASE_AZURE=true  -e DATABASE_TIMEOUT=5000  -e ID_SERIE_MAX_PRE_VENDA=230  -e ID_SERIE_MAX_REGULAR=229  -e ID_SERIE_JA_18=88  -e ID_SERIE_JA_17=89  -e ID_PRODUTO_MAX=1  -e VALIDADE_ANO_CARTAO="27"  graziela.azurecr.io/1.0:latest  rspec spec/test/spec_login.rb -fd'