# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master

trigger:
- master
- test

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:

# - stage: Build
#   displayName: Build image
#   jobs:  
#   - job: Build
#     displayName: Build
#     pool:
#       vmImage: 'ubuntu-latest'
#     steps:
#     - task: Docker@2
#       displayName: Build an image
#       inputs:
#         command: build
#         dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
#         tags: |
#           $(tag)


  - stage: BuildAndPush
    displayName: Build image
    jobs: 
    - job: Build
      displayName: Build
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: Docker@2
          displayName: Build and Push
          inputs:
            containerRegistry: 'graziela|azure'
            repository: '1.0'
            command: buildAndPush
            Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
            tags: |
              $(Build.BuildId)
              latest


  - stage: Run
    displayName: Run image
    jobs:  
    - job: Run
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      displayName: Run
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: CmdLine@2
        displayName: Pull image
        inputs:
          script: 'docker pull graziela.azurecr.io/1.0:latest' 
      - task: CmdLine@2
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        displayName: Running tests
        inputs:
          script: 'docker run -it graziela.azurecr.io/1.0:latest rspec spec/test/* -fd'
     
    # - task: Docker@2
    #   displayName: Build an image
      
    #   inputs:
    #     command: build
    #     dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    #     tags: |
    #       $(tag)

# - stage: Run
#   displayName: Build image
#   jobs:  
#   - job: Run
#     steps: 
#     - task: CmdLine@2
#       inputs:
#         script: 'echo graziela'